D:\setup.exe /Q `
/IACCEPTSQLSERVERLICENSETERMS `
/ACTION="install" `
/FEATURES=SQLEngine `
/INSTANCENAME=NamedMSSQLSERVER `
/SECURITYMODE=SQL `
/SAPWD="Str0ngP@ssw0rd" `
/SQLSYSADMINACCOUNTS="Administrator" `
/SQLUSERDBDIR="E:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Data" `
/SQLUSERDBLOGDIR="E:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\Data"